### ISSUE TITLE
Plotting Taylor and target plots

### ISSUE THREAD

**Issue by jyoti1singh** [PeterRochford/SkillMetricsToolbox#1]
Hi,
I am Jyoti Singh, a PhD student at IIT Delhi. I am using SkillMetricsToolbox-master for choosing some models for India from CMIP6. I am using MATLAB 2015b. While plotting Taylor/Target diagram there is error message:
Undefined function or variable 'xticks'.
Error in get_taylor_diagram_axes (line 44)
    xt = xticks;
Error in taylor_diagram (line 144)
[axes, cax, option] = get_taylor_diagram_axes(rho,option);
What may be the reason.
Apart from that while calculating Taylor/target statistics again there is an error:
Subscript indices must either be real positive integers or logical.
My data has NaN values so I have to remove it?

**Comment by PeterRochford** [comment]
Yes, your data cannot have any NaN values. This could be why you are encountering this error.
