### ISSUE TITLE
RMS value for circle

### ISSUE THREAD

**Issue by Krys1202** [PeterRochford/SkillMetricsToolbox#2]
Hi!
Thanks a lot for this toolbox.
I just have a problem to display the value of the RMS circles : my values are in the range [0 - 0.003], and on the diagram I can't manage to display 0 / 0.1/1 instead it's 0/0/1.
Could you help me please?

Regards,
Christelle

![taylor_BS2019_SEt](https://user-images.githubusercontent.com/36248064/72870660-e1921200-3d3c-11ea-9d08-51975e6e7483.png)

**Comment by PeterRochford** [comment]
See Q10 on the [FAQ](https://github.com/PeterRochford/SkillMetricsToolbox/wiki/FAQ).
