### ISSUE TITLE
Error occurs with text function

### ISSUE THREAD

**Issue by Ideschepper** [PeterRochford/SkillMetricsToolbox#3]
Hello,
I am trying to use the taylor_diagram function, but I continue to get the following error: 

Error using text First two or three arguments must be numeric doubles.

Error in overlay_taylor_diagram_circles (line 79) ttt(ic) = text(xtextpos,ytextpos, ...

Error in taylor_diagram (line 148) axes = overlay_taylor_diagram_circles(axes,cax,option);

Any idea how I can fix this problem? I am using Matlab R2019a. Thanks

**Comment by PeterRochford** [comment]
This problem should no longer occur because the values stored in xtextpos and ytextpos variables are now converted to doubles.
